(function() {var implementors = {};
implementors["libc"] = [];implementors["ntru"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ntru/types/struct.IntPoly.html' title='ntru::types::IntPoly'>IntPoly</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ntru/types/struct.TernPoly.html' title='ntru::types::TernPoly'>TernPoly</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ntru/types/struct.ProdPoly.html' title='ntru::types::ProdPoly'>ProdPoly</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ntru/types/struct.PrivPoly.html' title='ntru::types::PrivPoly'>PrivPoly</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ntru/types/struct.PrivateKey.html' title='ntru::types::PrivateKey'>PrivateKey</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ntru/types/struct.PublicKey.html' title='ntru::types::PublicKey'>PublicKey</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ntru/types/struct.KeyPair.html' title='ntru::types::KeyPair'>KeyPair</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ntru/rand/struct.RandContext.html' title='ntru::rand::RandContext'>RandContext</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='ntru/encparams/struct.EncParams.html' title='ntru::encparams::EncParams'>EncParams</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
